/* Autogenerated with kurento-module-creator */

#include "CarsDetected.hpp"
#include <jsonrpc/JsonSerializer.hpp>
#include <chrono>
#include <ctime>
#include <string>

namespace kurento
{
namespace module
{
namespace cardetector
{

void
CarsDetected::Serialize (JsonSerializer &s)
{
  Media::Serialize (s);

  s.SerializeNVP (carsDetected);
  s.SerializeNVP (idCam);
}

} /* cardetector */
} /* module */
} /* kurento */

namespace kurento
{

void Serialize (std::shared_ptr<kurento::module::cardetector::CarsDetected> &event, JsonSerializer &s)
{
  if (!s.IsWriter && !event) {
    event.reset (new kurento::module::cardetector::CarsDetected() );
  }

  if (event) {
    event->Serialize (s);
  }
}

} /* kurento */
