/* Autogenerated with kurento-module-creator */

#include "CarDetectorImpl.hpp"
#include "CarsDetected.hpp"

#include <jsonrpc/JsonSerializer.hpp>

namespace kurento
{
namespace module
{
namespace cardetector
{

void dummyCardetector ()
{
  {
    JsonSerializer s (true);
    std::shared_ptr<CarDetector> object;

    s.SerializeNVP (object);
  }
  {
    JsonSerializer s (true);
    std::shared_ptr<CarsDetected> object;

    s.SerializeNVP (object);
  }
}

} /* cardetector */
} /* module */
} /* kurento */
